name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # main 브랜치에 push될 때 실행

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 저장소 클론
        uses: actions/checkout@v3

      - name: Docker 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker 이미지 빌드 및 태깅
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ais-tracking:latest .
          docker tag ${{ secrets.DOCKER_USERNAME }}/ais-tracking:latest ${{ secrets.DOCKER_USERNAME }}/ais-tracking:v1.0

      - name: Docker Hub에 푸시
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ais-tracking:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/ais-tracking:v1.0
